### PR TITLE
Remove recurring send

### PR DESCRIPTION
**Pull request by shane-kerr**
This removes the "recurring send" functionality, which does not work or do anything as far as I can tell.

This addresses issue #68.

### CODE REVIEW

**Comment by Myke500** [comment]
Has anyone tried to use it? It's basically like a smart contract no?

**Comment by shane-kerr** [comment]
As far as I can tell, there's nothing to try. Using the option brings up a blank window.

Clearly the intention was to set up an automated send. Looking at the code, the idea was _NOT_ for it to be like a smart contract (so executed by the blockchain itself), but rather the wallet itself would periodically send coins.

That probably made more sense when the wallet was lightweight and people could reasonably be expected to keep it on all the time. Nowadays it's a fat 2 Gbyte pig in RAM and many people just run it every 20 days to mint their coins. ;-)

If it worked and people were relying on it then it might be a bigger deal. If someone complains we can always revert the change.

**Comment by Myke500** [comment]
I know I had it set up on the ok'd wallet, but only every 100 days. It
never got that far before the wallet issues started so I can't confirm if
it really worked 💯

**Comment by shane-kerr** [comment]
Ah, mystery solved. From https://github.com/MintcoinCommunity/MintCoin-Docs/blob/master/Announcements/2.0-Proposed_Revisions.md:

Improved RecurringSend Documentation. RecurringSend is a feature that allows a person to setup recurring transactions. While the feature works as intended when Coin Control is disabled, RecurringSend and Coin Control are mutually exclusive features. When Coin Control is enabled, the RecurringSend pane appears blank. The proposed change is to add in-pane explanation of this in the RecurringSend pane when Coin Control is enabled.

So I have coin control enabled, so I don't see it!

Clearly more thought is needed here. I'll cancel this PR.

**Pull request closed without merging**
